# Arquivo de exemplo para configuração de secrets
# Para usar, descomente a linha abaixo e adicione sua chave real

GEMINI_API_KEY = "AIzaSyBAMF9R5O15JwulpP0c44Px_s8O1Dt6HCc"

# Instruções:
# 1. Obtenha sua chave em: https://makersuite.google.com/app/apikey
# 2. Descomente a linha acima e substitua pela sua chave real
# 3. Para Streamlit Cloud, adicione nos Secrets do app

